language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-22.0.1
    - android-22
    - sys-img-armeabi-v7a-android-22
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2b549dc5cbcc5470ee11
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
