language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-26.0.0
    - android-26
    - sys-img-armeabi-v7a-android-26
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2b549dc5cbcc5470ee11
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
licenses:
    - 'android-sdk-license-.+'
before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
install:
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-26.0.0
  - echo y | android update sdk -u -a -t android-26
