language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-26.0.0
    - android-26
    - sys-img-armeabi-v7a-android-26
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2b549dc5cbcc5470ee11
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
licenses:
    - 'android-sdk-license-.+'
install:
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-26.0.0
  - echo y | android update sdk -u -a -t android-26
